### ISSUE TITLE
error: failed to run custom build command for `audiopus_sys v0.1.7`

### ISSUE THREAD

**Issue by mscofield0** [serenity-rs/serenity#1001]
This happens with the `stable-x86_64-pc-windows-gnu` as of the date of this issue.
OS: Windows 7

```
D:/Coding/__Rust/Cargo/bin/cargo.exe build --color=always --all --all-targets
   Compiling net2 v0.2.35
   Compiling socket2 v0.3.15
   Compiling ring v0.16.15
   Compiling schannel v0.1.19
   Compiling winreg v0.7.0
   Compiling time v0.1.44
   Compiling audiopus_sys v0.1.7
error: failed to run custom build command for `audiopus_sys v0.1.7`

Caused by:
  process didn't exit successfully: `.\target\debug\build\audiopus_sys-914d4c3846a4717a\build-script-build` (exit code: 101)
  --- stdout
  cargo:info=No feature or environment variable found, linking by default.
  cargo:rerun-if-env-changed=OPUS_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:info=`pkg_config` could not find `Opus`.
  cargo:info=Opus source path: "\\\\?\\D:\\Coding\\__Rust\\Cargo\\registry\\src\\github.com-1ecc6299db9ec823\\audiopus_sys-0.1.7\\opus".
  cargo:info=Opus will be built as static-library.

  --- stderr
  thread 'main' panicked at 'Failed to copy Opus files to: D:\Coding\__GIT\Rust\DerelictBotany\target\debug\build\audiopus_sys-144702e7ccbe0bed\out: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', D:\Coding\__Rust\Cargo\registry\src\github.com-1ecc6299db9ec823\audiopus_sys-0.1.7\build.rs:82:10
  stack backtrace:
     0: backtrace::backtrace::dbghelp::trace
               at C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace/dbghelp.rs:88
     1: backtrace::backtrace::trace_unsynchronized
               at C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace/mod.rs:66
     2: std::sys_common::backtrace::_print_fmt
               at src\libstd\sys_common/backtrace.rs:78
     3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
               at src\libstd\sys_common/backtrace.rs:59
     4: core::fmt::write
               at src\libcore\fmt/mod.rs:1076
     5: std::io::Write::write_fmt
               at src\libstd\io/mod.rs:1537
     6: std::sys_common::backtrace::_print
               at src\libstd\sys_common/backtrace.rs:62
     7: std::sys_common::backtrace::print
               at src\libstd\sys_common/backtrace.rs:49
     8: std::panicking::default_hook::{{closure}}
               at src\libstd/panicking.rs:198
     9: std::panicking::default_hook
               at src\libstd/panicking.rs:217
    10: std::panicking::rust_panic_with_hook
               at src\libstd/panicking.rs:526
    11: rust_begin_unwind
               at src\libstd/panicking.rs:437
    12: core::panicking::panic_fmt
               at src\libcore/panicking.rs:85
    13: core::option::expect_none_failed
               at src\libcore/option.rs:1269
    14: core::result::Result<T,E>::expect
               at D:\Coding\__Rust\Rustup\toolchains\stable-x86_64-pc-windows-gnu\lib/rustlib/src/rust\src\libcore/result.rs:963
    15: build_script_build::build_opus
               at .\build.rs:77
    16: build_script_build::main
               at .\build.rs:338
    17: std::rt::lang_start::{{closure}}
               at D:\Coding\__Rust\Rustup\toolchains\stable-x86_64-pc-windows-gnu\lib/rustlib/src/rust\src\libstd/rt.rs:67
    18: std::rt::lang_start_internal::{{closure}}
               at src\libstd/rt.rs:52
    19: std::panicking::try::do_call
               at src\libstd/panicking.rs:348
    20: std::panicking::try
               at src\libstd/panicking.rs:325
    21: std::panic::catch_unwind
               at src\libstd/panic.rs:394
    22: std::rt::lang_start_internal
               at src\libstd/rt.rs:51
    23: std::rt::lang_start
               at D:\Coding\__Rust\Rustup\toolchains\stable-x86_64-pc-windows-gnu\lib/rustlib/src/rust\src\libstd/rt.rs:67
    24: main
    25: __tmainCRTStartup
               at D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:339
    26: mainCRTStartup
               at D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:223
    27: units_search
    28: units_search
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by kangalio** [comment]
Does this issue still happen with songbird 0.3.0? It depends on audiopus 0.3.0-rc.0, which, according to the linked issue in serenity-rs/songbird, fixes the problem
