### ISSUE TITLE
Messages sent containing attachments do not handle rate limits correctly

### ISSUE THREAD

**Issue by ghost** [serenity-rs/serenity#1556]
Serenity version: Both `0.10.9` and latest git
Rust version (`rustc -V`): rustc 1.55.0 (c8dfcfe04 2021-09-06)
Backtrace (make sure to run `RUST_BACKTRACE=1`):
(i'd suggest reading the rest of this issue before analyzing it, it's only included to fill the template)
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Http(UnsuccessfulRequest(ErrorResponse { status_code: 429, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("discord.com")), port: None, path: "/api/v9/channels/891592197382742056/messages", query: None, fragment: None }, error: DiscordJsonError { code: -1, message: "[Serenity] Could not decode json when receiving error response from discord!", errors: [] } }))', src/main.rs:22:106
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1281:23
   4: scratchpad::main::{{closure}}
             at ./src/main.rs:22:5
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/future/mod.rs:80:19
   6: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/squili/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/park/thread.rs:263:54
   7: tokio::coop::with_budget::{{closure}}
             at /home/squili/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:106:9
   8: std::thread::local::LocalKey<T>::try_with
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/thread/local.rs:399:16
   9: std::thread::local::LocalKey<T>::with
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/thread/local.rs:375:9
  10: tokio::coop::with_budget
             at /home/squili/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:99:5
  11: tokio::coop::budget
             at /home/squili/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:76:5
  12: tokio::park::thread::CachedParkThread::block_on
             at /home/squili/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/park/thread.rs:263:31
  13: tokio::runtime::enter::Enter::block_on
             at /home/squili/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/enter.rs:151:13
  14: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/squili/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/thread_pool/mod.rs:77:9
  15: tokio::runtime::Runtime::block_on
             at /home/squili/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/mod.rs:463:43
  16: scratchpad::main
             at ./src/main.rs:24:5
  17: core::ops::function::FnOnce::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
```
Minimal test case:
```rs
let http = Http::new_with_token("abc");
let target_channel = ChannelId(123);

// trigger ratelimit
target_channel.send_message(&http, |m| m.content("1")).await.unwrap();
target_channel.send_message(&http, |m| m.content("2")).await.unwrap();
target_channel.send_message(&http, |m| m.content("3")).await.unwrap();
target_channel.send_message(&http, |m| m.content("4")).await.unwrap();
target_channel.send_message(&http, |m| m.content("5")).await.unwrap();

// upload image
target_channel.send_message(&http, |m| m.add_file(AttachmentType::Path("image.png".as_ref()))).await.unwrap();
```

What I think is the issue:

Looking at the code path for messages that don't contain an attachment, it uses the `Http::request` method, [which sets up a `RatelimitedRequest`](https://github.com/serenity-rs/serenity/blob/b21f053b87d611d0f803cdfbc232b70621daa3ab/src/http/client.rs#L3354). For messages _with_ an attachment, however, [Http::send_files](https://github.com/serenity-rs/serenity/blob/b21f053b87d611d0f803cdfbc232b70621daa3ab/src/http/client.rs#L2984) never calls any sort of rate limiting system.

As for why it didn't report a rate limit error, rate limits use [a different structure of error responses](https://discord.com/developers/docs/topics/rate-limits#exceeding-a-rate-limit-rate-limit-response-structure) than normal errors. I assume that there is no explicit handling for this because you're never supposed to have a rate limit error at this point in the code. You can recreate this case by setting the `http.ratelimiter_disabled` parameter to true. If you do this, you'll see that you get the same error.

**Comment by drklee3** [comment]
Ratelimiting with attachments is fixed in the `next` branch, the PR for reference: #1408

**Comment by ghost** [comment]
ah, didn't think to check that. thanks!
