### ISSUE TITLE
Framework Feature was not provided? 

### ISSUE THREAD

**Issue by slayernominee** [serenity-rs/serenity#2339]
thread 'main' panicked at 'The `framework`-feature is enabled (it's on by default), but no framework was provided.
If you don't want to use the command framework, disable default features and specify all features you want to use.', /Users/zero/.cargo/registry/src/github.com-1ecc6299db9ec823/serenity-0.11.5/src/client/mod.rs:361:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

im just trying to run the ping pong bot example what am i doing wrong?

**Comment by slayernominee** [comment]
```

stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_display
   3: core::panicking::panic_str
   4: core::option::expect_failed
   5: core::option::Option<T>::expect
             at /private/tmp/rust-20230126-6490-p3fvrc/rustc-1.67.0-src/library/core/src/option.rs:741:21
   6: <serenity::client::ClientBuilder as core::future::future::Future>::poll
             at /Users/zero/.cargo/registry/src/github.com-1ecc6299db9ec823/serenity-0.11.5/src/client/mod.rs:360:29
   7: bot::main::{{closure}}
             at ./src/main.rs:53:64
   8: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/zero/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/park.rs:283:63
   9: tokio::runtime::coop::with_budget
             at /Users/zero/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:102:5
  10: tokio::runtime::coop::budget
             at /Users/zero/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:68:5
  11: tokio::runtime::park::CachedParkThread::block_on
             at /Users/zero/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/park.rs:283:31
  12: tokio::runtime::context::BlockingRegionGuard::block_on
             at /Users/zero/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/context.rs:315:13
  13: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/zero/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  14: tokio::runtime::runtime::Runtime::block_on
             at /Users/zero/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/runtime.rs:284:45
  15: bot::main
             at ./src/main.rs:59:5
  16: core::ops::function::FnOnce::call_once
             at /private/tmp/rust-20230126-6490-p3fvrc/rustc-1.67.0-src/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by slayernominee** [comment]
and this is the full one 

```
stack backtrace:
   0:        0x103ba2b74 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9b8941a7f101aacd
   1:        0x103bbb9dc - core::fmt::write::hf679be18bf0a7a41
   2:        0x103b8b190 - std::io::Write::write_fmt::h81377ba11f45c742
   3:        0x103ba2984 - std::sys_common::backtrace::print::h3c1f856e83e7a7f5
   4:        0x103b9afb4 - std::panicking::default_hook::{{closure}}::h7e712100bebc7b6c
   5:        0x103b9ad4c - std::panicking::default_hook::h3ad129828935eefe
   6:        0x103b9b560 - std::panicking::rust_panic_with_hook::hbad225085fd8d838
   7:        0x103ba3168 - std::panicking::begin_panic_handler::{{closure}}::h0e451bf5d8753ad6
   8:        0x103ba2cb4 - std::sys_common::backtrace::__rust_end_short_backtrace::h780843ed7de7f569
   9:        0x103b9b154 - _rust_begin_unwind
  10:        0x103bd27e0 - core::panicking::panic_fmt::h55cdd1b3cc9ea97f
  11:        0x103bb7934 - core::panicking::panic_display::h03234e11b6f5c9d1
  12:        0x103bb78f8 - core::panicking::panic_str::h7325da8685df2df7
  13:        0x103bd2718 - core::option::expect_failed::h9d013aec7a6087c0
  14:        0x103235af8 - core::option::Option<T>::expect::h7b0b613ce7a4f8db
                               at /private/tmp/rust-20230126-6490-p3fvrc/rustc-1.67.0-src/library/core/src/option.rs:741:21
  15:        0x1033641b8 - <serenity::client::ClientBuilder as core::future::future::Future>::poll::h93218270edea9623
                               at /Users/zero/.cargo/registry/src/github.com-1ecc6299db9ec823/serenity-0.11.5/src/client/mod.rs:360:29
  16:        0x102dc3fe0 - bot::main::{{closure}}::hacfcf361d0d18c2a
                               at /Users/zero/Library/Mobile Documents/com~apple~CloudDocs/Development/Projekte/Rust-Discord-Bot/bot/src/main.rs:53:64
  17:        0x102db0010 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::he6363aa443ddf309
                               at /Users/zero/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/park.rs:283:63
  18:        0x102dafe64 - tokio::runtime::coop::with_budget::hf5cf8abb36ddfee0
                               at /Users/zero/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:102:5
  19:        0x102dafe64 - tokio::runtime::coop::budget::hbb3c18c6670f22d5
                               at /Users/zero/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:68:5
  20:        0x102dafe64 - tokio::runtime::park::CachedParkThread::block_on::h40a99481162569fc
                               at /Users/zero/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/park.rs:283:31
  21:        0x102dc50a8 - tokio::runtime::context::BlockingRegionGuard::block_on::h5bfafe3e42735b95
                               at /Users/zero/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/context.rs:315:13
  22:        0x102dc44f0 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h03ff1e52112283f9
                               at /Users/zero/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  23:        0x102db36dc - tokio::runtime::runtime::Runtime::block_on::hd5708bd29e58fad5
                               at /Users/zero/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/runtime.rs:284:45
  24:        0x102dcf998 - bot::main::h3763c162c2db32cd
                               at /Users/zero/Library/Mobile Documents/com~apple~CloudDocs/Development/Projekte/Rust-Discord-Bot/bot/src/main.rs:59:5
  25:        0x102db92d8 - core::ops::function::FnOnce::call_once::hbf83a266105f4b4e
                               at /private/tmp/rust-20230126-6490-p3fvrc/rustc-1.67.0-src/library/core/src/ops/function.rs:507:5
  26:        0x102db34d4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1a4f06aa83fe4046
                               at /private/tmp/rust-20230126-6490-p3fvrc/rustc-1.67.0-src/library/std/src/sys_common/backtrace.rs:121:18
  27:        0x102daf778 - std::rt::lang_start::{{closure}}::h72833c7a0416162c
                               at /private/tmp/rust-20230126-6490-p3fvrc/rustc-1.67.0-src/library/std/src/rt.rs:166:18
  28:        0x103b91190 - std::rt::lang_start_internal::h39bbe85852d884c9
  29:        0x102daf744 - std::rt::lang_start::hcb8cf91def02694d
                               at /private/tmp/rust-20230126-6490-p3fvrc/rustc-1.67.0-src/library/std/src/rt.rs:165:17
  30:        0x102dcfa30 - _main
```

**Comment by slayernominee** [comment]
![code](https://user-images.githubusercontent.com/64646271/216784761-b7b15ec9-2595-42d4-aa93-a02cb4f827e4.png)

**Comment by slayernominee** [comment]
ah sry i found what i made wrong I included the complete serenity
