### ISSUE TITLE
Error building ring

### ISSUE THREAD

**Issue by valcubeto** [serenity-rs/serenity#2579]
**I got this output with cargo build, run, and clippy**:
```
   Compiling ring v0.17.5
   Compiling ring v0.16.20
The following warnings were emitted during compilation:

warning: crypto/curve25519/curve25519.c:1:0: sorry, unimplemented: 64-bit mode not compiled in
warning:  /* Copyright (c) 2020, Google Inc.
warning:  

error: failed to run custom build command for `ring v0.17.5`

Caused by:
  process didn't exit successfully: `C:\Rust\buki\target\debug\build\ring-a6d4c616585edd54\build-script-build` (exit code: 1)  
  --- stdout
  cargo:rerun-if-env-changed=RING_PREGENERATE_ASM
  cargo:rustc-env=RING_CORE_PREFIX=ring_core_0_17_5_
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-pc-windows-gnu")
  HOST = Some("x86_64-pc-windows-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-pc-windows-gnu
  CC_x86_64-pc-windows-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_pc_windows_gnu
  CC_x86_64_pc_windows_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-pc-windows-gnu
  CFLAGS_x86_64-pc-windows-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_pc_windows_gnu
  CFLAGS_x86_64_pc_windows_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  running: "gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-gdwarf-2" "-fno-omit-frame-pointer" "-m64" "-I" "include" 
"-I" "C:\\Rust\\buki\\target\\debug\\build\\ring-f77d4c07ada79a70\\out" "-Wall" "-Wextra" "-fvisibility=hidden" "-std=c1x" "-pedantic" "-Wall" "-Wextra" "-Wbad-function-cast" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wnested-externs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wstrict-prototypes" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-g3" "-DNDEBUG" "-o" "C:\\Rust\\buki\\target\\debug\\build\\ring-f77d4c07ada79a70\\out\\crypto/curve25519/curve25519.o" "-c" "crypto/curve25519/curve25519.c"
  __cargo:warning=crypto/curve25519/curve25519.c:1:0: sorry, unimplemented: 64-bit mode not compiled in__

  __cargo:warning= /* Copyright (c) 2020, Google Inc.__

  __cargo:warning=__

  exit code: 1

  --- stderr


  error occurred: Command "gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-gdwarf-2" "-fno-omit-frame-pointer" "-m64" 
"-I" "include" "-I" "C:\\Rust\\buki\\target\\debug\\build\\ring-f77d4c07ada79a70\\out" "-Wall" "-Wextra" "-fvisibility=hidden" 
"-std=c1x" "-pedantic" "-Wall" "-Wextra" "-Wbad-function-cast" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wnested-externs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wstrict-prototypes" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-g3" "-DNDEBUG" "-o" "C:\\Rust\\buki\\target\\debug\\build\\ring-f77d4c07ada79a70\\out\\crypto/curve25519/curve25519.o" "-c" "crypto/curve25519/curve25519.c" with args "gcc.exe" did not execute successfully (status code exit code: 1).


warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `C:\Rust\buki\target\debug\build\ring-8da0a40e7333c094\build-script-build` (exit code: 101)  --- stdout
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-pc-windows-gnu")
  HOST = Some("x86_64-pc-windows-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-pc-windows-gnu
  CC_x86_64-pc-windows-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_pc_windows_gnu
  CC_x86_64_pc_windows_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-pc-windows-gnu
  CFLAGS_x86_64-pc-windows-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_pc_windows_gnu
  CFLAGS_x86_64_pc_windows_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None

  --- stderr
  running "gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-gdwarf-2" "-fno-omit-frame-pointer" "-m64" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" 
"-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-g3" "-DNDEBUG" "-c" "-oC:\\Rust\\buki\\target\\debug\\build\\ring-87bdae1512fb7272\\out\\aes_nohw.o" "crypto/fipsmodule/aes/aes_nohw.c"
  __crypto/fipsmodule/aes/aes_nohw.c:1:0: sorry, unimplemented: 64-bit mode not compiled in__
   __/* Copyright (c) 2019, Google Inc.__

  thread 'main' panicked at 'execution failed', C:\Users\valen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ring-0.16.20\build.rs:656:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**I ran `rustup update` (to 1.73.0, also failed when deleting a tmp file) and the output changed to this**:
```
   Checking cfg-if v1.0.0
   ...
    Checking bytes v1.5.0
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `C:\Rust\buki\target\debug\build\ring-a1678af766c289b9\build-script-build` (exit code: 101)  --- stdout
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-pc-windows-gnu")
  HOST = Some("x86_64-pc-windows-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-pc-windows-gnu
  CC_x86_64-pc-windows-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_pc_windows_gnu
  CC_x86_64_pc_windows_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-pc-windows-gnu
  CFLAGS_x86_64-pc-windows-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_pc_windows_gnu
  CFLAGS_x86_64_pc_windows_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None

  --- stderr
  running "gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-gdwarf-2" "-fno-omit-frame-pointer" "-m64" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" 
"-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-g3" "-DNDEBUG" "-c" "-oC:\\Rust\\buki\\target\\debug\\build\\ring-feb9b0bff42918b2\\out\\aes_nohw.o" "crypto/fipsmodule/aes/aes_nohw.c"
  __crypto/fipsmodule/aes/aes_nohw.c:1:0: sorry, unimplemented: 64-bit mode not compiled in__
   __/* Copyright (c) 2019, Google Inc.__

  thread 'main' panicked at C:\Users\valen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ring-0.16.20\build.rs:656:9:   
  execution failed
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**It seems that they just changed the warning displaying anyways. It makes no sense for me that Cargo prints a line of some Google license or something.**
**I tried changing some versions. GPT told me that I need to update OpenSSL, the Rust's Nightly version, MSVC (the installer crashed 2 times!). Nothing worked.**
**I keep trying because I saw people with my exact same device, arch, and OS building it fine.**
**Sorry if I wrote something wrong, English isn't my main language.**

**Comment by arqunis** [comment]
When installing GCC, did you make sure to install the 64-bit version? That's what the `sorry, unimplemented: 64-bit mode not compiled in__` message is complaining about; you're trying to compile in 64-bit mode with a 32-bit-only compiler.

**Comment by valcubeto** [comment]
> When installing GCC, did you make sure to install the 64-bit version?

`gcc --version` outputs this:
```
gcc (MinGW-W64 x86_64-msvcrt-posix-seh, built by Brecht Sanders) 13.1.0
```

I assume that it is the 64-bit version.

**Comment by valcubeto** [comment]
I forced cargo to use another version. this is `Cargo.toml`
```toml
# ...
[dependencies]
ring = { git = "https://github.com/briansmith/ring.git", branch = "master" }
```

It worked! Now I have another trouble with Perl because it doesn't recognize my locale settings, but it has nothing to do with Serenity or Ring.

**Comment by valcubeto** [comment]
Ok, I ran `$env:LC_ALL = "C"; cargo build` (because I speak C and not Spanish) and got this output:
```
warning: unused manifest key: package.target
   Compiling h2 v0.3.21
   Compiling ring v0.17.5 (https://github.com/briansmith/ring.git?branch=main#6920c4fc)
error: failed to run custom build command for `ring v0.17.5 (https://github.com/briansmith/ring.git?branch=main#6920c4fc)`

Caused by:
  process didn't exit successfully: `C:\Rust\buki\target\debug\build\ring-42848f38537e6fbd\build-script-build` (exit code: 101)  --- stdout
  cargo:rerun-if-env-changed=RING_PREGENERATE_ASM
  cargo:rustc-env=RING_CORE_PREFIX=ring_core_0_17_5_
  cargo:rerun-if-env-changed=PERL_EXECUTABLE
  cargo:rerun-if-env-changed=PERL_EXECUTABLE
  cargo:rerun-if-env-changed=PERL_EXECUTABLE
  cargo:rerun-if-env-changed=PERL_EXECUTABLE
  cargo:rerun-if-env-changed=PERL_EXECUTABLE
  cargo:rerun-if-env-changed=PERL_EXECUTABLE
  cargo:rerun-if-env-changed=PERL_EXECUTABLE
  cargo:rerun-if-env-changed=PERL_EXECUTABLE
  cargo:rerun-if-env-changed=PERL_EXECUTABLE
  cargo:rerun-if-env-changed=PERL_EXECUTABLE
  cargo:rerun-if-env-changed=PERL_EXECUTABLE
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-pc-windows-gnu")
  HOST = Some("x86_64-pc-windows-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-pc-windows-gnu
  CC_x86_64-pc-windows-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_pc_windows_gnu
  CC_x86_64_pc_windows_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-pc-windows-gnu
  CFLAGS_x86_64-pc-windows-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_pc_windows_gnu
  CFLAGS_x86_64_pc_windows_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None

  --- stderr
  running "perl" "crypto/chacha/asm/chacha-x86_64.pl" "nasm" "C:/Rust/buki/target/debug/build/ring-d4f10e1c1b66c65e/out/chacha-x86_64-nasm.asm"
  running "perl" "crypto/fipsmodule/aes/asm/aesni-x86_64.pl" "nasm" "C:/Rust/buki/target/debug/build/ring-d4f10e1c1b66c65e/out/aesni-x86_64-nasm.asm"
  running "perl" "crypto/fipsmodule/aes/asm/vpaes-x86_64.pl" "nasm" "C:/Rust/buki/target/debug/build/ring-d4f10e1c1b66c65e/out/vpaes-x86_64-nasm.asm"
  running "perl" "crypto/fipsmodule/bn/asm/x86_64-mont.pl" "nasm" "C:/Rust/buki/target/debug/build/ring-d4f10e1c1b66c65e/out/x86_64-mont-nasm.asm"
  running "perl" "crypto/fipsmodule/bn/asm/x86_64-mont5.pl" "nasm" "C:/Rust/buki/target/debug/build/ring-d4f10e1c1b66c65e/out/x86_64-mont5-nasm.asm"
  running "perl" "crypto/fipsmodule/ec/asm/p256-x86_64-asm.pl" "nasm" "C:/Rust/buki/target/debug/build/ring-d4f10e1c1b66c65e/out/p256-x86_64-asm-nasm.asm"
  running "perl" "crypto/fipsmodule/modes/asm/aesni-gcm-x86_64.pl" "nasm" "C:/Rust/buki/target/debug/build/ring-d4f10e1c1b66c65e/out/aesni-gcm-x86_64-nasm.asm"
  running "perl" "crypto/fipsmodule/modes/asm/ghash-x86_64.pl" "nasm" "C:/Rust/buki/target/debug/build/ring-d4f10e1c1b66c65e/out/ghash-x86_64-nasm.asm"
  running "perl" "crypto/fipsmodule/sha/asm/sha512-x86_64.pl" "nasm" "C:/Rust/buki/target/debug/build/ring-d4f10e1c1b66c65e/out/sha512-x86_64-nasm.asm"
  running "perl" "crypto/cipher_extra/asm/chacha20_poly1305_x86_64.pl" "nasm" "C:/Rust/buki/target/debug/build/ring-d4f10e1c1b66c65e/out/chacha20_poly1305_x86_64-nasm.asm"
  running "perl" "crypto/fipsmodule/sha/asm/sha512-x86_64.pl" "nasm" "C:/Rust/buki/target/debug/build/ring-d4f10e1c1b66c65e/out/sha256-x86_64-nasm.asm"
  running "./target/tools/windows/nasm/nasm" "-o" "C:\\Rust\\buki\\target\\debug\\build\\ring-d4f10e1c1b66c65e\\out\\chacha-x86_64-nasm.o" "-f" "win64" "-i" "include/" "-i" "C:\\Rust\\buki\\target\\debug\\build\\ring-d4f10e1c1b66c65e\\out\\" "-Xgnu" "-gcv8" "C:\\Rust\\buki\\target\\debug\\build\\ring-d4f10e1c1b66c65e\\out\\chacha-x86_64-nasm.asm"
  thread 'main' panicked at C:\Users\valen\.cargo\git\checkouts\ring-51509f604a4fd25b\6920c4f\build.rs:673:9:
  failed to execute ["./target/tools/windows/nasm/nasm" "-o" "C:\\Rust\\buki\\target\\debug\\build\\ring-d4f10e1c1b66c65e\\out\\chacha-x86_64-nasm.o" "-f" "win64" "-i" "include/" "-i" "C:\\Rust\\buki\\target\\debug\\build\\ring-d4f10e1c1b66c65e\\out\\" "-Xgnu" "-gcv8" "C:\\Rust\\buki\\target\\debug\\build\\ring-d4f10e1c1b66c65e\\out\\chacha-x86_64-nasm.asm"]: El sistema no puede encontrar la ruta especificada. (os error 3)
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

It seems that Perl didn't generate any output...

**Comment by kangalio** [comment]
Closing, since this seems unrelated to serenity itself. For assistance, you could ask in the Rust community discord, perhaps  `ring` has a place to ask for support as well.
