### ISSUE TITLE
Some channel names cause a panic inside of serenity::utils::is_nsfw

### ISSUE THREAD

**Issue by nitros12** [serenity-rs/serenity#342]
```
thread '<unnamed>' panicked at 'byte index 5 is not a char boundary; it is inside 'é' (bytes 4..6) of `général`', libcore/str/mod.rs>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:205
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:457
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:344
   6: rust_begin_unwind
             at libstd/panicking.rs:322
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::str::slice_error_fail
             at libcore/str/mod.rs:0
   9: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::RangeTo<usize>>::index::{{closure}}
  10: serenity::utils::is_nsfw
  11: <alloc::arc::Arc<parking_lot::rwlock::RwLock<T>> as serenity::internal::rwlock_ext::RwLockExt<T>>::with
  12: bot::utils::nsfw_check
  13: <serenity::framework::standard::StandardFramework as serenity::framework::Framework>::dispatch
  14: serenity::client::dispatch::dispatch
  15: <serenity::client::bridge::gateway::shard_runner::ShardRunner<H>>::run
```
Using serenity version: 0.5.4

**Comment by zeyla** [comment]
Thanks, should be fixed in that commit.
