### ISSUE TITLE
Compiling Serenity on AWS Ubuntu in 2020-01

### ISSUE THREAD

**Issue by mathieucaroff** [serenity-rs/serenity#760]
So I was trying to compile [Cosmic](https://github.com/Sreyas-Sreelal/Cosmic) on my AWS Ubuntu instance, and met a few problems. I published them with their solution [here, in Cosmic's bug tracker (#6)](https://github.com/Sreyas-Sreelal/Cosmic/issues/6). 

Here's a copy of the above issue to make it google-discoverable when searching for Serenity:

##### TL;DR

```
sudo apt update
sudo apt install -y pkg-config libssl-dev autoconf libtool libopus-dev
```

---

##### Story

I was getting the following error with `openssl-sys`:

```
ubuntu@ip-x-x-x-x:~/cosmic$ cargo build --release
   Compiling openssl-sys v0.9.53
error: failed to run custom build command for `openssl-sys v0.9.53`

Caused by:
  process didn't exit successfully: `/home/ubuntu/cosmic/target/release/build/openssl-sys-a58496d500b0ba7f/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
cargo:rerun-if-env-changed=OPENSSL_DIR
OPENSSL_DIR unset
run pkg_config fail: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"`: 
No such file or directory (os error 2)"

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

$HOST = x86_64-unknown-linux-gnu
$TARGET = x86_64-unknown-linux-gnu
openssl-sys = 0.9.53


It looks like you're compiling on Linux and also targeting Linux. Currently this
requires the `pkg-config` utility to find OpenSSL but unfortunately `pkg-config`
could not be found. If you have OpenSSL installed you can likely fix this by
installing `pkg-config`.

', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.53/build/find_normal.rs:150:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

So, as suggested by openssl-sys's error message, I did the following:

```
sudo apt update
sudo apt install -y libssl-dev pkg-config
```
---

Then I got the following error with `audiopus_sys`:

```
ubuntu@ip-172-31-38-14:~/cosmic$ cargo build --release
   Compiling audiopus_sys v0.1.5
error: failed to run custom build command for `audiopus_sys v0.1.5`

Caused by:
  process didn't exit successfully: `/home/ubuntu/cosmic/target/release/build/audiopus_sys-d46ad8915490dd23/build-script-build` (exit code: 101)
--- stdout
cargo:info=No feature or environment variable found, linking by default.
cargo:info=`pkg_config` could not find `Opus`.
cargo:info=Opus source path: "/home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/audiopus_sys-0.1.5/opus".
cargo:info=Opus will be built as dylib-library.
Updating build configuration files, please wait....

--- stderr
autogen.sh: 14: autogen.sh: autoreconf: not found
thread 'main' panicked at 'Failed to autogen Opus.', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/audiopus_sys-0.1.5/build.rs:81:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

So I installed autoconf:

```
sudo apt install -y autoconf
```

But then I got:

```
ubuntu@ip-172-31-38-14:~/cosmic$ cargo build --release
   Compiling audiopus_sys v0.1.5
error: failed to run custom build command for `audiopus_sys v0.1.5`

Caused by:
  process didn't exit successfully: `/home/ubuntu/cosmic/target/release/build/audiopus_sys-d46ad8915490dd23/build-script-build` (exit code: 101)
--- stdout
cargo:info=No feature or environment variable found, linking by default.
cargo:info=`pkg_config` could not find `Opus`.
cargo:info=Opus source path: "/home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/audiopus_sys-0.1.5/opus".
cargo:info=Opus will be built as dylib-library.
Updating build configuration files, please wait....

--- stderr
configure.ac:38: warning: macro 'AM_PROG_LIBTOOL' not found in library
configure.ac:38: error: possibly undefined macro: AM_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
thread 'main' panicked at 'Failed to autogen Opus.', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/audiopus_sys-0.1.5/build.rs:81:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

So I installed libtool:

```
sudo apt install -y libtool
```

---

and then it built.

---

Edit: Added `libopus-dev` to TL;DR.

**Comment by arqunis** [comment]
I am closing this issue. It's not a problem for Serenity in of itself, and more so that its dependencies can be built and found properly. Besides, it shouldn't affect google searches, the primary goal of this issue.

**Comment by mathieucaroff** [comment]
@acdenisSK 

> it shouldn't affect google searches, the primary goal of this issue

I'm curious, can you please expand on that?

**Comment by Erk-** [comment]
As far as I am aware cloed issues have the same seo as non closed one, and with the primary goal you stated that yourself
> Here's a copy of the above issue to make it google-discoverable when searching for Serenity:

It would be better to have it in the readme or wiki than in an issue.

**Comment by mathieucaroff** [comment]
Oh! Okay, @acdenisSK was referring to the open / closed status of the issue, not to its existence, I understand now.
